name: Keep Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  ping_server:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Server
        run: curl -X GET "https://ai-b.onrender.com/"
